### PR TITLE
Minitest nested

### LINKED ISSUE #21: Minitest nested test classes not working
### Your environment

- `vscode-ruby-test-adapter` version: 0.6.0
- Ruby version: 2.5.1
- VS Code version: 1.36.0
- Operating System: Ubuntu 18.04
- Minitest version: 5.11.3
- Rails version: 5.2.3

The app and all tests run in a docker container. The `vscode-ruby-test-adapter` also communicates via `docker-compose` commands

## specific vscode settings

```json
{
  "rubyTestExplorer.testFramework": "minitest",
  "rubyTestExplorer.minitestCommand": "docker-compose run --rm -e RAILS_ENV=test -e VSCODE=true api bundle exec rake",
}
```

## Test Setup

```ruby
require 'test_helper'

class MyTest < ActionController::TestCase
  setup do
    do_something
  end

  test 'test something' do
    assert something
  end

  class MyNestedTest < ActionController::TestCase
    setup do
      do_something_else
    end

    test 'test something else' do
      assert something_else
    end
  end
end
```

### Expected behavior

- the tests are listed and marked in the actual test file at the correct lines
- the tests can be run and report back

### Actual behavior

- the tests will be listed, but have a warning sign associated with them
  image
- running a test in the parent test class will run the correct test, report back, but not update the UI. Instead it shows a warning sign
  image
  Log Output:
  ```txt
  [2019-07-09 06:23:16.036] [INFO] Running Ruby tests ["./test/controllers/facility/versions_controller_test.rb[1:1:1]"]
  [2019-07-09 06:23:16.038] [INFO] Running single test: /home/[USER]/projects/[PROJECT]/test/controllers/facility/versions_controller_test.rb:14
  [2019-07-09 06:23:16.038] [INFO] Running command: docker-compose run --rm -e RAILS_ENV=test -e VSCODE=true api bundle exec rake -R $EXT_DIR vscode:minitest:run test/controllers/facility/versions_controller_test.rb:14
  [2019-07-09 06:23:20.357] [DEBUG] [CHILD PROCESS OUTPUT] 
  [2019-07-09 06:23:20.357] [DEBUG] [CHILD PROCESS OUTPUT] RUNNING: ./test/controllers/facility/versions_controller_test.rb[1:1:1]
  [2019-07-09 06:23:20.966] [DEBUG] [CHILD PROCESS OUTPUT] 
  [2019-07-09 06:23:20.966] [DEBUG] [CHILD PROCESS OUTPUT] PASSED: ./test/controllers/facility/versions_controller_test.rb[1:1:1]
  [2019-07-09 06:23:20.967] [DEBUG] [CHILD PROCESS OUTPUT] START_OF_TEST_JSON{"version":"5.11.3","summary":{"duration":2.12,"example_count":3,"failure_count":0,"pending_count":0,"errors_outside_of_examples_count":0},"summary_line":"Total time: 2.12, Runs: 1, Assertions: 3, Failures: 0, Errors: 0, Skips: 0","examples":[{"description":"should download file","full_description":"should download file","file_path":"./test/controllers/facility/versions_controller_test.rb","full_path":"/app/test/controllers/facility/versions_controller_test.rb","line_number":14,"klass":"Facility::VersionsControllerTest","method":"test_should_download_file","id":"./test/controllers/facility/versions_controller_test.rb[1:1:1]","status":"passed"}]}END_OF_TEST_JSON
  [2019-07-09 06:23:20.967] [DEBUG] Parsing the below JSON:
  [2019-07-09 06:23:20.967] [DEBUG] {"version":"5.11.3","summary":{"duration":2.12,"example_count":3,"failure_count":0,"pending_count":0,"errors_outside_of_examples_count":0},"summary_line":"Total time: 2.12, Runs: 1, Assertions: 3, Failures: 0, Errors: 0, Skips: 0","examples":[{"description":"should download file","full_description":"should download file","file_path":"./test/controllers/facility/versions_controller_test.rb","full_path":"/app/test/controllers/facility/versions_controller_test.rb","line_number":14,"klass":"Facility::VersionsControllerTest","method":"test_should_download_file","id":"./test/controllers/facility/versions_controller_test.rb[1:1:1]","status":"passed"}]}
  [2019-07-09 06:23:20.967] [DEBUG] Handling status of test: {"description":"should download file","full_description":"should download file","file_path":"./test/controllers/facility/versions_controller_test.rb","full_path":"/app/test/controllers/facility/versions_controller_test.rb","line_number":14,"klass":"Facility::VersionsControllerTest","method":"test_should_download_file","id":"./test/controllers/facility/versions_controller_test.rb[1:1:1]","status":"passed"}
  [2019-07-09 06:23:21.426] [INFO] Child process has exited. Sending test run finish event.
  ```
- running a test in the nested class will run the equivalent nth test from the parent class (the first nested test will run the first test from the parent class)
  image
  Log Output:
  ```txt
  [2019-07-09 06:30:03.703] [INFO] Running Ruby tests ["./test/controllers/facility/versions_controller_test.rb[1:1:1]"]
  [2019-07-09 06:30:03.703] [INFO] Running single test: /home/[USER]/projects/[PROJECT]/test/controllers/facility/versions_controller_test.rb:14
  [2019-07-09 06:30:03.704] [INFO] Running command: docker-compose run --rm -e RAILS_ENV=test -e VSCODE=true api bundle exec rake -R $EXT_DIR vscode:minitest:run test/controllers/facility/versions_controller_test.rb:14
  [2019-07-09 06:30:08.220] [DEBUG] [CHILD PROCESS OUTPUT] 
  [2019-07-09 06:30:08.220] [DEBUG] [CHILD PROCESS OUTPUT] RUNNING: ./test/controllers/facility/versions_controller_test.rb[1:1:1]
  [2019-07-09 06:30:08.902] [DEBUG] [CHILD PROCESS OUTPUT] 
  [2019-07-09 06:30:08.902] [DEBUG] [CHILD PROCESS OUTPUT] PASSED: ./test/controllers/facility/versions_controller_test.rb[1:1:1]
  [2019-07-09 06:30:08.903] [DEBUG] [CHILD PROCESS OUTPUT] START_OF_TEST_JSON{"version":"5.11.3","summary":{"duration":2.21,"example_count":3,"failure_count":0,"pending_count":0,"errors_outside_of_examples_count":0},"summary_line":"Total time: 2.21, Runs: 1, Assertions: 3, Failures: 0, Errors: 0, Skips: 0","examples":[{"description":"should download file","full_description":"should download file","file_path":"./test/controllers/facility/versions_controller_test.rb","full_path":"/app/test/controllers/facility/versions_controller_test.rb","line_number":14,"klass":"Facility::VersionsControllerTest","method":"test_should_download_file","id":"./test/controllers/facility/versions_controller_test.rb[1:1:1]","status":"passed"}]}END_OF_TEST_JSON
  [2019-07-09 06:30:08.903] [DEBUG] Parsing the below JSON:
  [2019-07-09 06:30:08.903] [DEBUG] {"version":"5.11.3","summary":{"duration":2.21,"example_count":3,"failure_count":0,"pending_count":0,"errors_outside_of_examples_count":0},"summary_line":"Total time: 2.21, Runs: 1, Assertions: 3, Failures: 0, Errors: 0, Skips: 0","examples":[{"description":"should download file","full_description":"should download file","file_path":"./test/controllers/facility/versions_controller_test.rb","full_path":"/app/test/controllers/facility/versions_controller_test.rb","line_number":14,"klass":"Facility::VersionsControllerTest","method":"test_should_download_file","id":"./test/controllers/facility/versions_controller_test.rb[1:1:1]","status":"passed"}]}
  [2019-07-09 06:30:08.904] [DEBUG] Handling status of test: {"description":"should download file","full_description":"should download file","file_path":"./test/controllers/facility/versions_controller_test.rb","full_path":"/app/test/controllers/facility/versions_controller_test.rb","line_number":14,"klass":"Facility::VersionsControllerTest","method":"test_should_download_file","id":"./test/controllers/facility/versions_controller_test.rb[1:1:1]","status":"passed"}
  [2019-07-09 06:30:09.340] [INFO] Child process has exited. Sending test run finish event.
  ```
- reporting on nested tests will again only show a warning sign
- a nested test that has no nth equivalent in the parent test class will run and report as usual (the parent test class has 3 tests; the 4th nested test will run normal and report correctly)

### PR DESCRIPTION
**Pull request by baelter**
Support nested minitests,
branched from #34 

Fixes #21

### CODE REVIEW

**Comment by connorshea** [comment]
Thanks! I'll test and review this in the next few days, please @ me if I haven't reviewed this or your other PR by Friday. :)

**Comment by baelter** [comment]
@connorshea

**Comment by baelter** [comment]
@connorshea :)

**Comment by connorshea** [comment]
Hmm, I get this error when trying this PR on my Rails app:

```
notificationsAlerts.ts:40 Command failed: bundle exec rake -R $EXT_DIR vscode:minitest:list rake aborted! KeyError: key not found: "TESTS_PATTERN" Did you mean?  "TESTS_DIR" /Users/connorshea/Programming/vscode-ruby-test-adapter/ruby/vscode/minitest/tests.rb:22:in `fetch' /Users/connorshea/Programming/vscode-ruby-test-adapter/ruby/vscode/minitest/tests.rb:22:in `load_files' /Users/connorshea/Programming/vscode-ruby-test-adapter/ruby/vscode/minitest/tests.rb:6:in `all' /Users/connorshea/Programming/vscode-ruby-test-adapter/ruby/vscode/minitest.rb:25:in `list' /Users/connorshea/Programming/vscode-ruby-test-adapter/ruby/vscode.rake:8:in `block (3 levels) in <top (required)>' /Users/connorshea/.rbenv/versions/2.5.3/bin/bundle:23:in `load' /Users/connorshea/.rbenv/versions/2.5.3/bin/bundle:23:in `<main>' Tasks: TOP => vscode:minitest:list (See full trace by running task with --trace)
```

**Comment by connorshea** [comment]
```
[2020-02-12 18:33:08.535] [renderer10] [error] Command failed: bundle exec rake -R $EXT_DIR vscode:minitest:list
rake aborted!
KeyError: key not found: "TESTS_PATTERN"
/Users/connorshea/Programming/vscode-ruby-test-adapter/ruby/vscode/minitest/tests.rb:23:in `fetch'
/Users/connorshea/Programming/vscode-ruby-test-adapter/ruby/vscode/minitest/tests.rb:23:in `load_files'
/Users/connorshea/Programming/vscode-ruby-test-adapter/ruby/vscode/minitest/tests.rb:6:in `all'
/Users/connorshea/Programming/vscode-ruby-test-adapter/ruby/vscode/minitest.rb:25:in `list'
/Users/connorshea/Programming/vscode-ruby-test-adapter/ruby/vscode.rake:8:in `block (3 levels) in <main>'
/Users/connorshea/.rbenv/versions/2.6.5/bin/bundle:23:in `load'
/Users/connorshea/.rbenv/versions/2.6.5/bin/bundle:23:in `<main>'
Tasks: TOP => vscode:minitest:list
(See full trace by running task with --trace)
: Error: Command failed: bundle exec rake -R $EXT_DIR vscode:minitest:list
rake aborted!
KeyError: key not found: "TESTS_PATTERN"
/Users/connorshea/Programming/vscode-ruby-test-adapter/ruby/vscode/minitest/tests.rb:23:in `fetch'
/Users/connorshea/Programming/vscode-ruby-test-adapter/ruby/vscode/minitest/tests.rb:23:in `load_files'
/Users/connorshea/Programming/vscode-ruby-test-adapter/ruby/vscode/minitest/tests.rb:6:in `all'
/Users/connorshea/Programming/vscode-ruby-test-adapter/ruby/vscode/minitest.rb:25:in `list'
/Users/connorshea/Programming/vscode-ruby-test-adapter/ruby/vscode.rake:8:in `block (3 levels) in <main>'
/Users/connorshea/.rbenv/versions/2.6.5/bin/bundle:23:in `load'
/Users/connorshea/.rbenv/versions/2.6.5/bin/bundle:23:in `<main>'
Tasks: TOP => vscode:minitest:list
(See full trace by running task with --trace)

    at ChildProcess.exithandler (child_process.js:303:12)
    at ChildProcess.emit (events.js:200:13)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:430:11)
    at Socket.emit (events.js:200:13)
    at Pipe.<anonymous> (net.js:586:12)
```

From trying to load the tests in https://github.com/connorshea/mdn-compat-data-explorer

**Comment by connorshea** [comment]
Oh, I may have forgotten to run the watch task and that's why it wasn't working 🤦‍♂ My bad.

**Comment by connorshea** [comment]
Regardless, I think you've waited long enough so I'll merge this. Thank you for the patience! :)

**Comment by baelter** [comment]
> Looks good to me. Only thing I'm not clear on is how the tests in `ruby/` work? Are they for manually testing the extension?

Yes, I just open them in vscode to verify that all looks ok.

**Pull request merged**
